# Generated by Django 3.1.2 on 2020-11-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_loginrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=32, verbose_name='hos')),
                ('result', models.TextField(default='***success***', verbose_name='result')),
                ('collect_time', models.DateTimeField(verbose_name='collect_time')),
                ('type', models.CharField(max_length=34, verbose_name='type')),
            ],
            options={
                'verbose_name': '采集日志',
                'verbose_name_plural': '采集日志',
                'db_table': 'collect_record',
            },
        ),
    ]
