# Generated by Django 3.1.2 on 2020-12-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteuserbindhost',
            name='platform',
            field=models.SmallIntegerField(choices=[(1, 'linux'), (2, 'windows'), (3, 'other')], default=1, verbose_name='平台'),
        ),
    ]
