# Generated by Django 3.1.2 on 2020-12-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_cpumonit_memorymonit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpumonit',
            options={'verbose_name': 'cpu监控', 'verbose_name_plural': 'cpu监控'},
        ),
        migrations.AlterModelOptions(
            name='memorymonit',
            options={'verbose_name': '内存监控', 'verbose_name_plural': '内存监控'},
        ),
        migrations.AlterModelTable(
            name='cpumonit',
            table='cpumonit',
        ),
        migrations.AlterModelTable(
            name='memorymonit',
            table='memorymonit',
        ),
    ]
